apiVersion: apps/v1
kind: Deployment
metadata:
  name: vre-home
  namespace: utility
  labels:
    app: vre-home
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vre-home
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: vre-home
        env: charite
    spec:
      imagePullSecrets:
        - name: registrypullsecret-tls
        - name: pilot-gitlab-registry-cred
        - name: charite-gitlab-registry-cred
        - name: bihealthdocker
      containers:
        - name: vre-home
          image: registry.bihealth.org:443/vre/frontend_vre_home:2b7c2d39
          ports:
            - containerPort: 80
          env:
          - name: env
            value: "charite"
          - name: REACT_APP_ENV
            value: "charite"
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf-vre-home
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1"
            limits:
              memory: "1000Mi"
              cpu: "1"
      nodeSelector:
        namespace: utility
      volumes:
        - name: nginx-conf-vre-home
          configMap:
            name: nginx-conf-vre-home
            items:
              - key: vre-home.conf
                path: vre-home.conf
---
apiVersion: v1
kind: Service
metadata:
  name: vre-home
  namespace: utility
  labels:
    app: vre-home
    env: charite
spec:
  ports:
  - name: vre-home
    port: 80
    targetPort: 80
  selector:
    app: vre-home
    env: charite
  type: ClusterIP
